name: AdvancedKits
main: com.fleynaro.advancedkits.Main
version: "2.0"
author: luca28pet, fleynaro, PetteriM1
api: ["1.0.0"]
description: Kit plugin for Nukkit
website: https://github.com/Nukkit-coders/AdvancedKits

commands:
 kit:
  description: Get a kit!
  usage: "/kit <kitName>"
  permission: advancedkits.command
 akreload:
  descrpition: Reload Kits settings
  usage: "/akreload"
  permission: advancedkits.admin
permissions:
 advancedkits.command:
  description: "Allows the user to run /kit command"
  default: true
 advancedkits.admin:
  description: "Allows the user to manage admin features"
  default: op